### PR TITLE
AsyncQueue-based AudioMixer

### LINKED ISSUE #566: AudioMixer is missing (but implementation exists :))
### Select which package(s) are affected

\@livekit/rtc-node

### Describe the bug

I found https://github.com/livekit/node-sdks/tree/brian/audio-mixer with a working implementaiton already,
what's blocking it from bringin it to main? :) 

Thanks
Simon

### Reproduction

-

### Logs

```shell

```

### System Info

```shell
-
```

### LiveKit server version

LiveKit cloud

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by simllll**
based on the work of @toubatbrian

manually tested + added test suite

VERY cpu friendly now too ;-)

fixes #566

### CODE REVIEW

File: packages/livekit-rtc/src/audio_mixer.ts [hunk 1]
```diff
@@ -0,0 +1,501 @@
...
+  }
+
+  get(): T | undefined {
+    const item = this.items.shift();
+    if (this.waitingProducers.length > 0) {
+      const resolve = this.waitingProducers.shift()!;
+      resolve(); // wakes up one waiting producer
+    }
+    return item;
+  }
```
Comment (toubatbrian) [inline packages/livekit-rtc/src/audio_mixer.ts]: Should we use a more efficient data structure, like an actual Queue?

File: packages/livekit-rtc/src/audio_mixer.ts [hunk 2]
```diff
@@ -0,0 +1,501 @@
...
+        console.log('AudioMixer: No streams available, waiting...');
+        // Wait for a stream to be added (signal queue will have an item)
+        await this.streamSignal.waitForItem();
+        // Consume the signal
+        this.streamSignal.get();
+        console.log('AudioMixer: Woken up, checking streams again...');
+        continue;
+      }
+
+      console.log(`AudioMixer: Processing ${this.streams.size} streams...`);
```
Comment (toubatbrian) [inline packages/livekit-rtc/src/audio_mixer.ts]: Once we finish testing, let's remove the `console.log`

File: packages/livekit-rtc/src/audio_mixer.ts (hunk 1 above)
Comment (simllll) [reply packages/livekit-rtc/src/audio_mixer.ts]: the reason why I introduced AsyncQueue is that this queue has consomers und producers to queue. So we can remove a lot of logic from the rest of the code, by just wating (e.g. await put(..)) till the queue is not full anymore, or the queue is not empty again.

File: packages/livekit-rtc/src/audio_mixer.ts (hunk 2 above)
Comment (simllll) [reply packages/livekit-rtc/src/audio_mixer.ts]: Oh I missed that, sorry

File: packages/livekit-rtc/src/audio_mixer.ts (hunk 1 above)
Comment (simllll) [reply packages/livekit-rtc/src/audio_mixer.ts]: added a comment in the code that explains it too.

File: packages/livekit-rtc/src/audio_mixer.ts (hunk 2 above)
Comment (simllll) [reply packages/livekit-rtc/src/audio_mixer.ts]: removed the console logs

File: packages/livekit-rtc/src/audio_mixer.ts (hunk 1 above)
Comment (toubatbrian) [reply packages/livekit-rtc/src/audio_mixer.ts]: oh just to clarify I mean specifically the `this.waitingConsumers.shift()` operation which is O(n), can we use something like a deque for the consumer and producers: https://datastructures-js.info/docs/deque? I think overall the idea of AsyncQueue looks great!

Comment (simllll) [reply packages/livekit-rtc/src/audio_mixer.ts]: Ah now I understand :)

Not sure if it's worth it to add a new dependency? I could also just implement a simple O(1) list-based queue internally? I'm following your suggestion, let me know ;-)

Comment (toubatbrian) [reply packages/livekit-rtc/src/audio_mixer.ts]: Yeah for me a list-based queue is also fine. @lukasIO let me know your thought

Comment (simllll) [reply packages/livekit-rtc/src/audio_mixer.ts]: ` import { Deque } from '@datastructures-js/deque'` it is ;-) less code to mantain is always better. and if a new dependency is okay, then let's do it. it's quite small too.

File: packages/livekit-rtc/src/audio_mixer.ts [hunk 3]
```diff
@@ -0,0 +1,472 @@
...
+      resolve();
+    }
+  }
+
+  get(): T | undefined {
+    const item = this.items.shift();
+    if (this.waitingProducers.size() > 0) {
+      const resolve = this.waitingProducers.popFront()!;
+      resolve(); // wakes up one waiting producer
+    }
```
Comment (toubatbrian) [inline packages/livekit-rtc/src/audio_mixer.ts]: can we add some tests to AsyncQueue as well?

File: packages/livekit-rtc/package.json [hunk 4]
```diff
@@ -47,18 +47,19 @@
   },
   "dependencies": {
     "@bufbuild/protobuf": "^1.10.1",
+    "@datastructures-js/deque": "^1.0.8",
```
Comment (ai-simple-ai) [inline packages/livekit-rtc/package.json]: This package has only one maintainer and only about 2 thousand downloads per week. Does it make sense to vendor this dependency into the repository to make sure it doesn't become an attack vector?

At the very least, does it make sense to pin the specific version of the repository without the semver?

Comment (lukasIO) [reply packages/livekit-rtc/package.json]: +1 for pinning

Comment (toubatbrian) [reply packages/livekit-rtc/package.json]: > This package has only one maintainer and only about 2 thousand downloads per week. Does it make sense to vendor this dependency into the repository to make sure it doesn't become an attack vector?

Good point. Given that we only use the `Deque` data structure from their package. Perhaps it make sense if we directly copy the code source file? https://github.com/datastructures-js/deque/blob/main/src/deque.js and add a reference comment https://github.com/datastructures-js/deque/blob/main/LICENSE
