### PR TITLE
Reject bad request response

### LINKED ISSUE #22: StartRecording throws an uncatchable axios error
I'm running livekit-server-sdk 0.5.9  and livekit-server v0.15.5 in service mode with redis

when I try to startRecording using the server-sdk-js and no recorders are available, I get a huge error being thrown by axios, that cannot be catched.

here's a snip of the code I use

```
'use strict';
const lksdk = require('livekit-server-sdk');
const RecordingServiceClient = require("livekit-server-sdk/dist/RecordingServiceClient").default
const RecordingTemplate = require('livekit-server-sdk/dist/proto/livekit_recording').RecordingTemplate;
const recService = new RecordingServiceClient("http://livekit:7880", process.env.LIVEKIT_API_KEY, process.env.LIVEKIT_API_SECRET);

async function startRecording(roomName) {
  const filename = roomName + ".mp4";
  const tpl = RecordingTemplate.fromJSON({
    layout: "grid-dark",
    roomName: roomName,
  });

  try {
    await recService.startRecording(tpl, filename);
  } catch (e) {
    console.log("error recording:", e);
  }
}
```

the error being thrown by axios is not catched at all, even though I startRecording() in a try/catch block

<details>
  <summary>here's the complete error I get (it's huge)</summary>

```
 /app/node_modules/axios/lib/core/createError.js:16
   var error = new Error(message);
               ^

 Error: Request failed with status code 500
     at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
     at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
     at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:269:11)
     at IncomingMessage.emit (node:events:402:35)
     at endReadableNT (node:internal/streams/readable:1343:12)
     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
   config: {
     url: '/twirp/livekit.RecordingService/StartRecording',
     method: 'post',
     data: '{"template":{"layout":"grid-dark","roomName":"NT0C5SD2HCWS5KO8SHJEO","baseUrl":""},"filepath":"NT0C5SD2HCWS5KO8SHJEO.mp4"}',
     headers: {
       Accept: 'application/json, text/plain, */*',
       'Content-Type': 'application/json',
       Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tUmVjb3JkIjp0cnVlfSwiaWF0IjoxNjQ2MjkyNDU4LCJuYmYiOjE2NDYyOTI0NTgsImV4cCI6MTY0NjI5MzA1OCwiaXNzIjoiQVBJRU5XRnRSYkxWY2NrIn0.eBFy0hg4Ss18kR8OWWcImdpAo1jeVeRXxa4DsGTH6I0',
       'User-Agent': 'axios/0.21.4',
       'Content-Length': 122
     },
     baseURL: 'http://livekit:7880',
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 0,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     maxBodyLength: -1,
     validateStatus: [Function: validateStatus],
     transitional: {
       silentJSONParsing: true,
       forcedJSONParsing: true,
       clarifyTimeoutError: false
     }
   },
   request: <ref *1> ClientRequest {
     _events: [Object: null prototype] {
       abort: [Function (anonymous)],
       aborted: [Function (anonymous)],
       connect: [Function (anonymous)],
       error: [Function (anonymous)],
       socket: [Function (anonymous)],
       timeout: [Function (anonymous)],
       prefinish: [Function: requestOnPrefinish]
     },
     _eventsCount: 7,
     _maxListeners: undefined,
     outputData: [],
     outputSize: 0,
     writable: true,
     destroyed: false,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     maxRequestsOnConnectionReached: false,
     _defaultKeepAlive: true,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: null,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     _closed: false,
     socket: <ref *2> Socket {
       connecting: false,
       _hadError: false,
       _parent: null,
       _host: 'livekit',
       _readableState: ReadableState {
         objectMode: false,
         highWaterMark: 16384,
         buffer: BufferList { head: null, tail: null, length: 0 },
         length: 0,
         pipes: [],
         flowing: true,
         ended: false,
         endEmitted: false,
         reading: true,
         constructed: true,
         sync: false,
         needReadable: true,
         emittedReadable: false,
         readableListening: false,
         resumeScheduled: false,
         errorEmitted: false,
         emitClose: false,
         autoDestroy: true,
         destroyed: false,
         errored: null,
         closed: false,
         closeEmitted: false,
         defaultEncoding: 'utf8',
         awaitDrainWriters: null,
         multiAwaitDrain: false,
         readingMore: false,
         dataEmitted: true,
         decoder: null,
         encoding: null,
         [Symbol(kPaused)]: false
       },
       _events: [Object: null prototype] {
         end: [Function: onReadableStreamEnd],
         free: [Function: onFree],
         close: [ [Function: onClose], [Function: socketCloseListener] ],
         timeout: [Function: onTimeout],
         agentRemove: [Function: onRemove],
         error: [Function: socketErrorListener],
         finish: [Function: bound onceWrapper] { listener: [Function: destroy] }
       },
       _eventsCount: 7,
       _maxListeners: undefined,
       _writableState: WritableState {
         objectMode: false,
         highWaterMark: 16384,
         finalCalled: true,
         needDrain: false,
         ending: true,
         ended: true,
         finished: false,
         destroyed: false,
         decodeStrings: false,
         defaultEncoding: 'utf8',
         length: 0,
         writing: false,
         corked: 0,
         sync: false,
         bufferProcessing: false,
         onwrite: [Function: bound onwrite],
         writecb: null,
         writelen: 0,
         afterWriteTickInfo: null,
         buffered: [],
         bufferedIndex: 0,
         allBuffers: true,
         allNoop: true,
         pendingcb: 1,
         constructed: true,
         prefinished: false,
         errorEmitted: false,
         emitClose: false,
         autoDestroy: true,
         errored: null,
         closed: false,
         closeEmitted: false,
         [Symbol(kOnFinished)]: []
       },
       allowHalfOpen: false,
       _sockname: null,
       _pendingData: null,
       _pendingEncoding: '',
       server: null,
       _server: null,
       parser: null,
       _httpMessage: [Circular *1],
       [Symbol(async_id_symbol)]: 282,
       [Symbol(kHandle)]: TCP {
         reading: true,
         onconnection: null,
         [Symbol(owner_symbol)]: [Circular *2]
       },
       [Symbol(kSetNoDelay)]: false,
       [Symbol(lastWriteQueueSize)]: 0,
       [Symbol(timeout)]: null,
       [Symbol(kBuffer)]: null,
       [Symbol(kBufferCb)]: null,
       [Symbol(kBufferGen)]: null,
       [Symbol(kCapture)]: false,
       [Symbol(kBytesRead)]: 0,
       [Symbol(kBytesWritten)]: 0,
       [Symbol(RequestTimeout)]: undefined
     },
     _header: 'POST /twirp/livekit.RecordingService/StartRecording HTTP/1.1\r\n' +
       'Accept: application/json, text/plain, */*\r\n' +
       'Content-Type: application/json\r\n' +
       'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tUmVjb3JkIjp0cnVlfSwiaWF0IjoxNjQ2MjkyNDU4LCJuYmYiOjE2NDYyOTI0NTgsImV4cCI6MTY0NjI5MzA1OCwiaXNzIjoiQVBJRU5XRnRSYkxWY2NrIn0.eBFy0hg4Ss18kR8OWWcImdpAo1jeVeRXxa4DsGTH6I0\r\n' +
       'User-Agent: axios/0.21.4\r\n' +
       'Content-Length: 122\r\n' +
       'Host: livekit:7880\r\n' +
       'Connection: close\r\n' +
       '\r\n',
     _keepAliveTimeout: 0,
     _onPendingData: [Function: nop],
     agent: Agent {
       _events: [Object: null prototype] {
         free: [Function (anonymous)],
         newListener: [Function: maybeEnableKeylog]
       },
       _eventsCount: 2,
       _maxListeners: undefined,
       defaultPort: 80,
       protocol: 'http:',
       options: [Object: null prototype] { path: null },
       requests: [Object: null prototype] {},
       sockets: [Object: null prototype] {
         'livekit:7880:': [
           <ref *2> Socket {
             connecting: false,
             _hadError: false,
             _parent: null,
             _host: 'livekit',
             _readableState: [ReadableState],
             _events: [Object: null prototype],
             _eventsCount: 7,
             _maxListeners: undefined,
             _writableState: [WritableState],
             allowHalfOpen: false,
             _sockname: null,
             _pendingData: null,
             _pendingEncoding: '',
             server: null,
             _server: null,
             parser: null,
             _httpMessage: [Circular *1],
             [Symbol(async_id_symbol)]: 282,
             [Symbol(kHandle)]: [TCP],
             [Symbol(kSetNoDelay)]: false,
             [Symbol(lastWriteQueueSize)]: 0,
             [Symbol(timeout)]: null,
             [Symbol(kBuffer)]: null,
             [Symbol(kBufferCb)]: null,
             [Symbol(kBufferGen)]: null,
             [Symbol(kCapture)]: false,
             [Symbol(kBytesRead)]: 0,
             [Symbol(kBytesWritten)]: 0,
             [Symbol(RequestTimeout)]: undefined
           }
         ]
       },
       freeSockets: [Object: null prototype] {},
       keepAliveMsecs: 1000,
       keepAlive: false,
       maxSockets: Infinity,
       maxFreeSockets: 256,
       scheduling: 'lifo',
       maxTotalSockets: Infinity,
       totalSocketCount: 1,
       [Symbol(kCapture)]: false
     },
     socketPath: undefined,
     method: 'POST',
     maxHeaderSize: undefined,
     insecureHTTPParser: undefined,
     path: '/twirp/livekit.RecordingService/StartRecording',
     _ended: true,
     res: IncomingMessage {
       _readableState: ReadableState {
         objectMode: false,
         highWaterMark: 16384,
         buffer: BufferList { head: null, tail: null, length: 0 },
         length: 0,
         pipes: [],
         flowing: true,
         ended: true,
         endEmitted: true,
         reading: false,
         constructed: true,
         sync: true,
         needReadable: false,
         emittedReadable: false,
         readableListening: false,
         resumeScheduled: false,
         errorEmitted: false,
         emitClose: true,
         autoDestroy: true,
         destroyed: true,
         errored: null,
         closed: true,
         closeEmitted: true,
         defaultEncoding: 'utf8',
         awaitDrainWriters: null,
         multiAwaitDrain: false,
         readingMore: true,
         dataEmitted: true,
         decoder: null,
         encoding: null,
         [Symbol(kPaused)]: false
       },
       _events: [Object: null prototype] {
         end: [ [Function: responseOnEnd], [Function: handleStreamEnd] ],
         data: [Function: handleStreamData],
         error: [Function: handleStreamError]
       },
       _eventsCount: 3,
       _maxListeners: undefined,
       socket: <ref *2> Socket {
         connecting: false,
         _hadError: false,
         _parent: null,
         _host: 'livekit',
         _readableState: ReadableState {
           objectMode: false,
           highWaterMark: 16384,
           buffer: BufferList { head: null, tail: null, length: 0 },
           length: 0,
           pipes: [],
           flowing: true,
           ended: false,
           endEmitted: false,
           reading: true,
           constructed: true,
           sync: false,
           needReadable: true,
           emittedReadable: false,
           readableListening: false,
           resumeScheduled: false,
           errorEmitted: false,
           emitClose: false,
           autoDestroy: true,
           destroyed: false,
           errored: null,
           closed: false,
           closeEmitted: false,
           defaultEncoding: 'utf8',
           awaitDrainWriters: null,
           multiAwaitDrain: false,
           readingMore: false,
           dataEmitted: true,
           decoder: null,
           encoding: null,
           [Symbol(kPaused)]: false
         },
         _events: [Object: null prototype] {
           end: [Function: onReadableStreamEnd],
           free: [Function: onFree],
           close: [ [Function: onClose], [Function: socketCloseListener] ],
           timeout: [Function: onTimeout],
           agentRemove: [Function: onRemove],
           error: [Function: socketErrorListener],
           finish: [Function: bound onceWrapper] {
             listener: [Function: destroy]
           }
         },
         _eventsCount: 7,
         _maxListeners: undefined,
         _writableState: WritableState {
           objectMode: false,
           highWaterMark: 16384,
           finalCalled: true,
           needDrain: false,
           ending: true,
           ended: true,
           finished: false,
           destroyed: false,
           decodeStrings: false,
           defaultEncoding: 'utf8',
           length: 0,
           writing: false,
           corked: 0,
           sync: false,
           bufferProcessing: false,
           onwrite: [Function: bound onwrite],
           writecb: null,
           writelen: 0,
           afterWriteTickInfo: null,
           buffered: [],
           bufferedIndex: 0,
           allBuffers: true,
           allNoop: true,
           pendingcb: 1,
           constructed: true,
           prefinished: false,
           errorEmitted: false,
           emitClose: false,
           autoDestroy: true,
           errored: null,
           closed: false,
           closeEmitted: false,
           [Symbol(kOnFinished)]: []
         },
         allowHalfOpen: false,
         _sockname: null,
         _pendingData: null,
         _pendingEncoding: '',
         server: null,
         _server: null,
         parser: null,
         _httpMessage: [Circular *1],
         [Symbol(async_id_symbol)]: 282,
         [Symbol(kHandle)]: TCP {
           reading: true,
           onconnection: null,
           [Symbol(owner_symbol)]: [Circular *2]
         },
         [Symbol(kSetNoDelay)]: false,
         [Symbol(lastWriteQueueSize)]: 0,
         [Symbol(timeout)]: null,
         [Symbol(kBuffer)]: null,
         [Symbol(kBufferCb)]: null,
         [Symbol(kBufferGen)]: null,
         [Symbol(kCapture)]: false,
         [Symbol(kBytesRead)]: 0,
         [Symbol(kBytesWritten)]: 0,
         [Symbol(RequestTimeout)]: undefined
       },
       httpVersionMajor: 1,
       httpVersionMinor: 1,
       httpVersion: '1.1',
       complete: true,
       rawHeaders: [
         'Content-Length',
         '89',
         'Content-Type',
         'application/json',
         'Vary',
         'Origin',
         'Date',
         'Thu, 03 Mar 2022 07:27:41 GMT',
         'Connection',
         'close'
       ],
       rawTrailers: [],
       aborted: false,
       upgrade: false,
       url: '',
       method: null,
       statusCode: 500,
       statusMessage: 'Internal Server Error',
       client: <ref *2> Socket {
         connecting: false,
         _hadError: false,
         _parent: null,
         _host: 'livekit',
         _readableState: ReadableState {
           objectMode: false,
           highWaterMark: 16384,
           buffer: BufferList { head: null, tail: null, length: 0 },
           length: 0,
           pipes: [],
           flowing: true,
           ended: false,
           endEmitted: false,
           reading: true,
           constructed: true,
           sync: false,
           needReadable: true,
           emittedReadable: false,
           readableListening: false,
           resumeScheduled: false,
           errorEmitted: false,
           emitClose: false,
           autoDestroy: true,
           destroyed: false,
           errored: null,
           closed: false,
           closeEmitted: false,
           defaultEncoding: 'utf8',
           awaitDrainWriters: null,
           multiAwaitDrain: false,
           readingMore: false,
           dataEmitted: true,
           decoder: null,
           encoding: null,
           [Symbol(kPaused)]: false
         },
         _events: [Object: null prototype] {
           end: [Function: onReadableStreamEnd],
           free: [Function: onFree],
           close: [ [Function: onClose], [Function: socketCloseListener] ],
           timeout: [Function: onTimeout],
           agentRemove: [Function: onRemove],
           error: [Function: socketErrorListener],
           finish: [Function: bound onceWrapper] {
             listener: [Function: destroy]
           }
         },
         _eventsCount: 7,
         _maxListeners: undefined,
         _writableState: WritableState {
           objectMode: false,
           highWaterMark: 16384,
           finalCalled: true,
           needDrain: false,
           ending: true,
           ended: true,
           finished: false,
           destroyed: false,
           decodeStrings: false,
           defaultEncoding: 'utf8',
           length: 0,
           writing: false,
           corked: 0,
           sync: false,
           bufferProcessing: false,
           onwrite: [Function: bound onwrite],
           writecb: null,
           writelen: 0,
           afterWriteTickInfo: null,
           buffered: [],
           bufferedIndex: 0,
           allBuffers: true,
           allNoop: true,
           pendingcb: 1,
           constructed: true,
           prefinished: false,
           errorEmitted: false,
           emitClose: false,
           autoDestroy: true,
           errored: null,
           closed: false,
           closeEmitted: false,
           [Symbol(kOnFinished)]: []
         },
         allowHalfOpen: false,
         _sockname: null,
         _pendingData: null,
         _pendingEncoding: '',
         server: null,
         _server: null,
         parser: null,
         _httpMessage: [Circular *1],
         [Symbol(async_id_symbol)]: 282,
         [Symbol(kHandle)]: TCP {
           reading: true,
           onconnection: null,
           [Symbol(owner_symbol)]: [Circular *2]
         },
         [Symbol(kSetNoDelay)]: false,
         [Symbol(lastWriteQueueSize)]: 0,
         [Symbol(timeout)]: null,
         [Symbol(kBuffer)]: null,
         [Symbol(kBufferCb)]: null,
         [Symbol(kBufferGen)]: null,
         [Symbol(kCapture)]: false,
         [Symbol(kBytesRead)]: 0,
         [Symbol(kBytesWritten)]: 0,
         [Symbol(RequestTimeout)]: undefined
       },
       _consuming: false,
       _dumped: false,
       req: [Circular *1],
       responseUrl: 'http://livekit:7880/twirp/livekit.RecordingService/StartRecording',
       redirects: [],
       [Symbol(kCapture)]: false,
       [Symbol(kHeaders)]: {
         'content-length': '89',
         'content-type': 'application/json',
         vary: 'Origin',
         date: 'Thu, 03 Mar 2022 07:27:41 GMT',
         connection: 'close'
       },
       [Symbol(kHeadersCount)]: 10,
       [Symbol(kTrailers)]: null,
       [Symbol(kTrailersCount)]: 0,
       [Symbol(RequestTimeout)]: undefined
     },
     aborted: false,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     reusedSocket: false,
     host: 'livekit',
     protocol: 'http:',
     _redirectable: Writable {
       _writableState: WritableState {
         objectMode: false,
         highWaterMark: 16384,
         finalCalled: false,
         needDrain: false,
         ending: false,
         ended: false,
         finished: false,
         destroyed: false,
         decodeStrings: true,
         defaultEncoding: 'utf8',
         length: 0,
         writing: false,
         corked: 0,
         sync: true,
         bufferProcessing: false,
         onwrite: [Function: bound onwrite],
         writecb: null,
         writelen: 0,
         afterWriteTickInfo: null,
         buffered: [],
         bufferedIndex: 0,
         allBuffers: true,
         allNoop: true,
         pendingcb: 0,
         constructed: true,
         prefinished: false,
         errorEmitted: false,
         emitClose: true,
         autoDestroy: true,
         errored: null,
         closed: false,
         closeEmitted: false,
         [Symbol(kOnFinished)]: []
       },
       _events: [Object: null prototype] {
         response: [Function: handleResponse],
         error: [Function: handleRequestError]
       },
       _eventsCount: 2,
       _maxListeners: undefined,
       _options: {
         maxRedirects: 21,
         maxBodyLength: 10485760,
         protocol: 'http:',
         path: '/twirp/livekit.RecordingService/StartRecording',
         method: 'POST',
         headers: {
           Accept: 'application/json, text/plain, */*',
           'Content-Type': 'application/json',
           Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tUmVjb3JkIjp0cnVlfSwiaWF0IjoxNjQ2MjkyNDU4LCJuYmYiOjE2NDYyOTI0NTgsImV4cCI6MTY0NjI5MzA1OCwiaXNzIjoiQVBJRU5XRnRSYkxWY2NrIn0.eBFy0hg4Ss18kR8OWWcImdpAo1jeVeRXxa4DsGTH6I0',
           'User-Agent': 'axios/0.21.4',
           'Content-Length': 122
         },
         agent: undefined,
         agents: { http: undefined, https: undefined },
         auth: undefined,
         hostname: 'livekit',
         port: '7880',
         nativeProtocols: {
           'http:': {
             _connectionListener: [Function: connectionListener],
             METHODS: [Array],
             STATUS_CODES: [Object],
             Agent: [Function],
             ClientRequest: [Function: ClientRequest],
             IncomingMessage: [Function: IncomingMessage],
             OutgoingMessage: [Function: OutgoingMessage],
             Server: [Function: Server],
             ServerResponse: [Function: ServerResponse],
             createServer: [Function: createServer],
             validateHeaderName: [Function: __node_internal_],
             validateHeaderValue: [Function: __node_internal_],
             get: [Function: get],
             request: [Function: request],
             maxHeaderSize: [Getter],
             globalAgent: [Getter/Setter]
           },
           'https:': {
             Agent: [Function: Agent],
             globalAgent: [Agent],
             Server: [Function: Server],
             createServer: [Function: createServer],
             get: [Function: get],
             request: [Function: request]
           }
         },
         pathname: '/twirp/livekit.RecordingService/StartRecording'
       },
       _ended: true,
       _ending: true,
       _redirectCount: 0,
       _redirects: [],
       _requestBodyLength: 122,
       _requestBodyBuffers: [],
       _onNativeResponse: [Function (anonymous)],
       _currentRequest: [Circular *1],
       _currentUrl: 'http://livekit:7880/twirp/livekit.RecordingService/StartRecording',
       [Symbol(kCapture)]: false
     },
     [Symbol(kCapture)]: false,
     [Symbol(kNeedDrain)]: false,
     [Symbol(corked)]: 0,
     [Symbol(kOutHeaders)]: [Object: null prototype] {
       accept: [ 'Accept', 'application/json, text/plain, */*' ],
       'content-type': [ 'Content-Type', 'application/json' ],
       authorization: [
         'Authorization',
         'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tUmVjb3JkIjp0cnVlfSwiaWF0IjoxNjQ2MjkyNDU4LCJuYmYiOjE2NDYyOTI0NTgsImV4cCI6MTY0NjI5MzA1OCwiaXNzIjoiQVBJRU5XRnRSYkxWY2NrIn0.eBFy0hg4Ss18kR8OWWcImdpAo1jeVeRXxa4DsGTH6I0'
       ],
       'user-agent': [ 'User-Agent', 'axios/0.21.4' ],
       'content-length': [ 'Content-Length', 122 ],
       host: [ 'Host', 'livekit:7880' ]
     }
   },
   response: {
     status: 500,
     statusText: 'Internal Server Error',
     headers: {
       'content-length': '89',
       'content-type': 'application/json',
       vary: 'Origin',
       date: 'Thu, 03 Mar 2022 07:27:41 GMT',
       connection: 'close'
     },
     config: {
       url: '/twirp/livekit.RecordingService/StartRecording',
       method: 'post',
       data: '{"template":{"layout":"grid-dark","roomName":"NT0C5SD2HCWS5KO8SHJEO","baseUrl":""},"filepath":"NT0C5SD2HCWS5KO8SHJEO.mp4"}',
       headers: {
         Accept: 'application/json, text/plain, */*',
         'Content-Type': 'application/json',
         Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tUmVjb3JkIjp0cnVlfSwiaWF0IjoxNjQ2MjkyNDU4LCJuYmYiOjE2NDYyOTI0NTgsImV4cCI6MTY0NjI5MzA1OCwiaXNzIjoiQVBJRU5XRnRSYkxWY2NrIn0.eBFy0hg4Ss18kR8OWWcImdpAo1jeVeRXxa4DsGTH6I0',
         'User-Agent': 'axios/0.21.4',
         'Content-Length': 122
       },
       baseURL: 'http://livekit:7880',
       transformRequest: [ [Function: transformRequest] ],
       transformResponse: [ [Function: transformResponse] ],
       timeout: 0,
       adapter: [Function: httpAdapter],
       xsrfCookieName: 'XSRF-TOKEN',
       xsrfHeaderName: 'X-XSRF-TOKEN',
       maxContentLength: -1,
       maxBodyLength: -1,
       validateStatus: [Function: validateStatus],
       transitional: {
         silentJSONParsing: true,
         forcedJSONParsing: true,
         clarifyTimeoutError: false
       }
     },
     request: <ref *1> ClientRequest {
       _events: [Object: null prototype] {
         abort: [Function (anonymous)],
         aborted: [Function (anonymous)],
         connect: [Function (anonymous)],
         error: [Function (anonymous)],
         socket: [Function (anonymous)],
         timeout: [Function (anonymous)],
         prefinish: [Function: requestOnPrefinish]
       },
       _eventsCount: 7,
       _maxListeners: undefined,
       outputData: [],
       outputSize: 0,
       writable: true,
       destroyed: false,
       _last: true,
       chunkedEncoding: false,
       shouldKeepAlive: false,
       maxRequestsOnConnectionReached: false,
       _defaultKeepAlive: true,
       useChunkedEncodingByDefault: true,
       sendDate: false,
       _removedConnection: false,
       _removedContLen: false,
       _removedTE: false,
       _contentLength: null,
       _hasBody: true,
       _trailer: '',
       finished: true,
       _headerSent: true,
       _closed: false,
       socket: <ref *2> Socket {
         connecting: false,
         _hadError: false,
         _parent: null,
         _host: 'livekit',
         _readableState: ReadableState {
           objectMode: false,
           highWaterMark: 16384,
           buffer: BufferList { head: null, tail: null, length: 0 },
           length: 0,
           pipes: [],
           flowing: true,
           ended: false,
           endEmitted: false,
           reading: true,
           constructed: true,
           sync: false,
           needReadable: true,
           emittedReadable: false,
           readableListening: false,
           resumeScheduled: false,
           errorEmitted: false,
           emitClose: false,
           autoDestroy: true,
           destroyed: false,
           errored: null,
           closed: false,
           closeEmitted: false,
           defaultEncoding: 'utf8',
           awaitDrainWriters: null,
           multiAwaitDrain: false,
           readingMore: false,
           dataEmitted: true,
           decoder: null,
           encoding: null,
           [Symbol(kPaused)]: false
         },
         _events: [Object: null prototype] {
           end: [Function: onReadableStreamEnd],
           free: [Function: onFree],
           close: [ [Function: onClose], [Function: socketCloseListener] ],
           timeout: [Function: onTimeout],
           agentRemove: [Function: onRemove],
           error: [Function: socketErrorListener],
           finish: [Function: bound onceWrapper] {
             listener: [Function: destroy]
           }
         },
         _eventsCount: 7,
         _maxListeners: undefined,
         _writableState: WritableState {
           objectMode: false,
           highWaterMark: 16384,
           finalCalled: true,
           needDrain: false,
           ending: true,
           ended: true,
           finished: false,
           destroyed: false,
           decodeStrings: false,
           defaultEncoding: 'utf8',
           length: 0,
           writing: false,
           corked: 0,
           sync: false,
           bufferProcessing: false,
           onwrite: [Function: bound onwrite],
           writecb: null,
           writelen: 0,
           afterWriteTickInfo: null,
           buffered: [],
           bufferedIndex: 0,
           allBuffers: true,
           allNoop: true,
           pendingcb: 1,
           constructed: true,
           prefinished: false,
           errorEmitted: false,
           emitClose: false,
           autoDestroy: true,
           errored: null,
           closed: false,
           closeEmitted: false,
           [Symbol(kOnFinished)]: []
         },
         allowHalfOpen: false,
         _sockname: null,
         _pendingData: null,
         _pendingEncoding: '',
         server: null,
         _server: null,
         parser: null,
         _httpMessage: [Circular *1],
         [Symbol(async_id_symbol)]: 282,
         [Symbol(kHandle)]: TCP {
           reading: true,
           onconnection: null,
           [Symbol(owner_symbol)]: [Circular *2]
         },
         [Symbol(kSetNoDelay)]: false,
         [Symbol(lastWriteQueueSize)]: 0,
         [Symbol(timeout)]: null,
         [Symbol(kBuffer)]: null,
         [Symbol(kBufferCb)]: null,
         [Symbol(kBufferGen)]: null,
         [Symbol(kCapture)]: false,
         [Symbol(kBytesRead)]: 0,
         [Symbol(kBytesWritten)]: 0,
         [Symbol(RequestTimeout)]: undefined
       },
       _header: 'POST /twirp/livekit.RecordingService/StartRecording HTTP/1.1\r\n' +
         'Accept: application/json, text/plain, */*\r\n' +
         'Content-Type: application/json\r\n' +
         'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tUmVjb3JkIjp0cnVlfSwiaWF0IjoxNjQ2MjkyNDU4LCJuYmYiOjE2NDYyOTI0NTgsImV4cCI6MTY0NjI5MzA1OCwiaXNzIjoiQVBJRU5XRnRSYkxWY2NrIn0.eBFy0hg4Ss18kR8OWWcImdpAo1jeVeRXxa4DsGTH6I0\r\n' +
         'User-Agent: axios/0.21.4\r\n' +
         'Content-Length: 122\r\n' +
         'Host: livekit:7880\r\n' +
         'Connection: close\r\n' +
         '\r\n',
       _keepAliveTimeout: 0,
       _onPendingData: [Function: nop],
       agent: Agent {
         _events: [Object: null prototype] {
           free: [Function (anonymous)],
           newListener: [Function: maybeEnableKeylog]
         },
         _eventsCount: 2,
         _maxListeners: undefined,
         defaultPort: 80,
         protocol: 'http:',
         options: [Object: null prototype] { path: null },
         requests: [Object: null prototype] {},
         sockets: [Object: null prototype] { 'livekit:7880:': [ [Socket] ] },
         freeSockets: [Object: null prototype] {},
         keepAliveMsecs: 1000,
         keepAlive: false,
         maxSockets: Infinity,
         maxFreeSockets: 256,
         scheduling: 'lifo',
         maxTotalSockets: Infinity,
         totalSocketCount: 1,
         [Symbol(kCapture)]: false
       },
       socketPath: undefined,
       method: 'POST',
       maxHeaderSize: undefined,
       insecureHTTPParser: undefined,
       path: '/twirp/livekit.RecordingService/StartRecording',
       _ended: true,
       res: IncomingMessage {
         _readableState: ReadableState {
           objectMode: false,
           highWaterMark: 16384,
           buffer: BufferList { head: null, tail: null, length: 0 },
           length: 0,
           pipes: [],
           flowing: true,
           ended: true,
           endEmitted: true,
           reading: false,
           constructed: true,
           sync: true,
           needReadable: false,
           emittedReadable: false,
           readableListening: false,
           resumeScheduled: false,
           errorEmitted: false,
           emitClose: true,
           autoDestroy: true,
           destroyed: true,
           errored: null,
           closed: true,
           closeEmitted: true,
           defaultEncoding: 'utf8',
           awaitDrainWriters: null,
           multiAwaitDrain: false,
           readingMore: true,
           dataEmitted: true,
           decoder: null,
           encoding: null,
           [Symbol(kPaused)]: false
         },
         _events: [Object: null prototype] {
           end: [ [Function: responseOnEnd], [Function: handleStreamEnd] ],
           data: [Function: handleStreamData],
           error: [Function: handleStreamError]
         },
         _eventsCount: 3,
         _maxListeners: undefined,
         socket: <ref *2> Socket {
           connecting: false,
           _hadError: false,
           _parent: null,
           _host: 'livekit',
           _readableState: ReadableState {
             objectMode: false,
             highWaterMark: 16384,
             buffer: [BufferList],
             length: 0,
             pipes: [],
             flowing: true,
             ended: false,
             endEmitted: false,
             reading: true,
             constructed: true,
             sync: false,
             needReadable: true,
             emittedReadable: false,
             readableListening: false,
             resumeScheduled: false,
             errorEmitted: false,
             emitClose: false,
             autoDestroy: true,
             destroyed: false,
             errored: null,
             closed: false,
             closeEmitted: false,
             defaultEncoding: 'utf8',
             awaitDrainWriters: null,
             multiAwaitDrain: false,
             readingMore: false,
             dataEmitted: true,
             decoder: null,
             encoding: null,
             [Symbol(kPaused)]: false
           },
           _events: [Object: null prototype] {
             end: [Function: onReadableStreamEnd],
             free: [Function: onFree],
             close: [Array],
             timeout: [Function: onTimeout],
             agentRemove: [Function: onRemove],
             error: [Function: socketErrorListener],
             finish: [Function]
           },
           _eventsCount: 7,
           _maxListeners: undefined,
           _writableState: WritableState {
             objectMode: false,
             highWaterMark: 16384,
             finalCalled: true,
             needDrain: false,
             ending: true,
             ended: true,
             finished: false,
             destroyed: false,
             decodeStrings: false,
             defaultEncoding: 'utf8',
             length: 0,
             writing: false,
             corked: 0,
             sync: false,
             bufferProcessing: false,
             onwrite: [Function: bound onwrite],
             writecb: null,
             writelen: 0,
             afterWriteTickInfo: null,
             buffered: [],
             bufferedIndex: 0,
             allBuffers: true,
             allNoop: true,
             pendingcb: 1,
             constructed: true,
             prefinished: false,
             errorEmitted: false,
             emitClose: false,
             autoDestroy: true,
             errored: null,
             closed: false,
             closeEmitted: false,
             [Symbol(kOnFinished)]: []
           },
           allowHalfOpen: false,
           _sockname: null,
           _pendingData: null,
           _pendingEncoding: '',
           server: null,
           _server: null,
           parser: null,
           _httpMessage: [Circular *1],
           [Symbol(async_id_symbol)]: 282,
           [Symbol(kHandle)]: TCP {
             reading: true,
             onconnection: null,
             [Symbol(owner_symbol)]: [Circular *2]
           },
           [Symbol(kSetNoDelay)]: false,
           [Symbol(lastWriteQueueSize)]: 0,
           [Symbol(timeout)]: null,
           [Symbol(kBuffer)]: null,
           [Symbol(kBufferCb)]: null,
           [Symbol(kBufferGen)]: null,
           [Symbol(kCapture)]: false,
           [Symbol(kBytesRead)]: 0,
           [Symbol(kBytesWritten)]: 0,
           [Symbol(RequestTimeout)]: undefined
         },
         httpVersionMajor: 1,
         httpVersionMinor: 1,
         httpVersion: '1.1',
         complete: true,
         rawHeaders: [
           'Content-Length',
           '89',
           'Content-Type',
           'application/json',
           'Vary',
           'Origin',
           'Date',
           'Thu, 03 Mar 2022 07:27:41 GMT',
           'Connection',
           'close'
         ],
         rawTrailers: [],
         aborted: false,
         upgrade: false,
         url: '',
         method: null,
         statusCode: 500,
         statusMessage: 'Internal Server Error',
         client: <ref *2> Socket {
           connecting: false,
           _hadError: false,
           _parent: null,
           _host: 'livekit',
           _readableState: ReadableState {
             objectMode: false,
             highWaterMark: 16384,
             buffer: [BufferList],
             length: 0,
             pipes: [],
             flowing: true,
             ended: false,
             endEmitted: false,
             reading: true,
             constructed: true,
             sync: false,
             needReadable: true,
             emittedReadable: false,
             readableListening: false,
             resumeScheduled: false,
             errorEmitted: false,
             emitClose: false,
             autoDestroy: true,
             destroyed: false,
             errored: null,
             closed: false,
             closeEmitted: false,
             defaultEncoding: 'utf8',
             awaitDrainWriters: null,
             multiAwaitDrain: false,
             readingMore: false,
             dataEmitted: true,
             decoder: null,
             encoding: null,
             [Symbol(kPaused)]: false
           },
           _events: [Object: null prototype] {
             end: [Function: onReadableStreamEnd],
             free: [Function: onFree],
             close: [Array],
             timeout: [Function: onTimeout],
             agentRemove: [Function: onRemove],
             error: [Function: socketErrorListener],
             finish: [Function]
           },
           _eventsCount: 7,
           _maxListeners: undefined,
           _writableState: WritableState {
             objectMode: false,
             highWaterMark: 16384,
             finalCalled: true,
             needDrain: false,
             ending: true,
             ended: true,
             finished: false,
             destroyed: false,
             decodeStrings: false,
             defaultEncoding: 'utf8',
             length: 0,
             writing: false,
             corked: 0,
             sync: false,
             bufferProcessing: false,
             onwrite: [Function: bound onwrite],
             writecb: null,
             writelen: 0,
             afterWriteTickInfo: null,
             buffered: [],
             bufferedIndex: 0,
             allBuffers: true,
             allNoop: true,
             pendingcb: 1,
             constructed: true,
             prefinished: false,
             errorEmitted: false,
             emitClose: false,
             autoDestroy: true,
             errored: null,
             closed: false,
             closeEmitted: false,
             [Symbol(kOnFinished)]: []
           },
           allowHalfOpen: false,
           _sockname: null,
           _pendingData: null,
           _pendingEncoding: '',
           server: null,
           _server: null,
           parser: null,
           _httpMessage: [Circular *1],
           [Symbol(async_id_symbol)]: 282,
           [Symbol(kHandle)]: TCP {
             reading: true,
             onconnection: null,
             [Symbol(owner_symbol)]: [Circular *2]
           },
           [Symbol(kSetNoDelay)]: false,
           [Symbol(lastWriteQueueSize)]: 0,
           [Symbol(timeout)]: null,
           [Symbol(kBuffer)]: null,
           [Symbol(kBufferCb)]: null,
           [Symbol(kBufferGen)]: null,
           [Symbol(kCapture)]: false,
           [Symbol(kBytesRead)]: 0,
           [Symbol(kBytesWritten)]: 0,
           [Symbol(RequestTimeout)]: undefined
         },
         _consuming: false,
         _dumped: false,
         req: [Circular *1],
         responseUrl: 'http://livekit:7880/twirp/livekit.RecordingService/StartRecording',
         redirects: [],
         [Symbol(kCapture)]: false,
         [Symbol(kHeaders)]: {
           'content-length': '89',
           'content-type': 'application/json',
           vary: 'Origin',
           date: 'Thu, 03 Mar 2022 07:27:41 GMT',
           connection: 'close'
         },
         [Symbol(kHeadersCount)]: 10,
         [Symbol(kTrailers)]: null,
         [Symbol(kTrailersCount)]: 0,
         [Symbol(RequestTimeout)]: undefined
       },
       aborted: false,
       timeoutCb: null,
       upgradeOrConnect: false,
       parser: null,
       maxHeadersCount: null,
       reusedSocket: false,
       host: 'livekit',
       protocol: 'http:',
       _redirectable: Writable {
         _writableState: WritableState {
           objectMode: false,
           highWaterMark: 16384,
           finalCalled: false,
           needDrain: false,
           ending: false,
           ended: false,
           finished: false,
           destroyed: false,
           decodeStrings: true,
           defaultEncoding: 'utf8',
           length: 0,
           writing: false,
           corked: 0,
           sync: true,
           bufferProcessing: false,
           onwrite: [Function: bound onwrite],
           writecb: null,
           writelen: 0,
           afterWriteTickInfo: null,
           buffered: [],
           bufferedIndex: 0,
           allBuffers: true,
           allNoop: true,
           pendingcb: 0,
           constructed: true,
           prefinished: false,
           errorEmitted: false,
           emitClose: true,
           autoDestroy: true,
           errored: null,
           closed: false,
           closeEmitted: false,
           [Symbol(kOnFinished)]: []
         },
         _events: [Object: null prototype] {
           response: [Function: handleResponse],
           error: [Function: handleRequestError]
         },
         _eventsCount: 2,
         _maxListeners: undefined,
         _options: {
           maxRedirects: 21,
           maxBodyLength: 10485760,
           protocol: 'http:',
           path: '/twirp/livekit.RecordingService/StartRecording',
           method: 'POST',
           headers: {
             Accept: 'application/json, text/plain, */*',
             'Content-Type': 'application/json',
             Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tUmVjb3JkIjp0cnVlfSwiaWF0IjoxNjQ2MjkyNDU4LCJuYmYiOjE2NDYyOTI0NTgsImV4cCI6MTY0NjI5MzA1OCwiaXNzIjoiQVBJRU5XRnRSYkxWY2NrIn0.eBFy0hg4Ss18kR8OWWcImdpAo1jeVeRXxa4DsGTH6I0',
             'User-Agent': 'axios/0.21.4',
             'Content-Length': 122
           },
           agent: undefined,
           agents: { http: undefined, https: undefined },
           auth: undefined,
           hostname: 'livekit',
           port: '7880',
           nativeProtocols: { 'http:': [Object], 'https:': [Object] },
           pathname: '/twirp/livekit.RecordingService/StartRecording'
         },
         _ended: true,
         _ending: true,
         _redirectCount: 0,
         _redirects: [],
         _requestBodyLength: 122,
         _requestBodyBuffers: [],
         _onNativeResponse: [Function (anonymous)],
         _currentRequest: [Circular *1],
         _currentUrl: 'http://livekit:7880/twirp/livekit.RecordingService/StartRecording',
         [Symbol(kCapture)]: false
       },
       [Symbol(kCapture)]: false,
       [Symbol(kNeedDrain)]: false,
       [Symbol(corked)]: 0,
       [Symbol(kOutHeaders)]: [Object: null prototype] {
         accept: [ 'Accept', 'application/json, text/plain, */*' ],
         'content-type': [ 'Content-Type', 'application/json' ],
         authorization: [
           'Authorization',
           'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tUmVjb3JkIjp0cnVlfSwiaWF0IjoxNjQ2MjkyNDU4LCJuYmYiOjE2NDYyOTI0NTgsImV4cCI6MTY0NjI5MzA1OCwiaXNzIjoiQVBJRU5XRnRSYkxWY2NrIn0.eBFy0hg4Ss18kR8OWWcImdpAo1jeVeRXxa4DsGTH6I0'
         ],
         'user-agent': [ 'User-Agent', 'axios/0.21.4' ],
         'content-length': [ 'Content-Length', 122 ],
         host: [ 'Host', 'livekit:7880' ]
       }
     },
     data: {
       code: 'internal',
       msg: 'no recorders available',
       meta: { cause: '*errors.errorString' }
     }
   },
   isAxiosError: true,
   toJSON: [Function: toJSON]
 }

```  

</details>

### LINKED ISSUE #123: updateParticipant throws uncatchable 500 error
I have an interval that is supposed to update the metadata for an ingress participant every second like this:

 ```const metadata = JSON.stringify({ timestamp: startTime, iteration: iteration });
      try {
        roomServiceClient.updateParticipant(room, ingressOptions.participantIdentity, metadata);
      } catch (error) {
        console.error(error);
      }
```
      
And it works some of the time, running the full ~200 times (length of the stream), but most of the time it will fail at some point and return an incredibly lengthy 500 error from Axios that is not being caught in the try catch. I don't really care if the request fails occasionally, but I really need it to not crash the script, so any guidance would be appreciated.

Seems perhaps related to this issue: https://github.com/livekit/server-sdk-js/issues/22

<details>
<summary>full error</summary>
<br>

```
C:\Users\thoma\metaverse\metaverse-backend\node_modules\axios\lib\core\settle.js:19
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 500
    at settle (C:\Users\thoma\metaverse\metaverse-backend\node_modules\axios\lib\core\settle.js:19:12)
    at IncomingMessage.handleStreamEnd (C:\Users\thoma\metaverse\metaverse-backend\node_modules\axios\lib\adapters\http.js:572:11)
    at IncomingMessage.emit (node:events:526:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_RESPONSE',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tQWRtaW4iOnRydWUsInJvb20iOiIxOmF2OjEifSwiaWF0IjoxNzAyNjAzMjYwLCJuYmYiOjE3MDI2MDMyNjAsImV4cCI6MTcwMjYwMzg2MCwiaXNzIjoiQVBJbUxBTnlBUE5Fa2tVIn0.LjGQsQFTcDmwQwowmf5Fr4674TPtMtxyuDNy8ayNPew',
      'User-Agent': 'axios/1.5.1',
      'Content-Length': '114',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: 'https://mkmv.livekit.cloud/',
    method: 'post',
    url: '/twirp/livekit.RoomService/UpdateParticipant',
    data: '{"room":"1:av:1","identity":"streaming_bot","metadata":"{\\"timestamp\\":1702603227817,\\"iteration\\":30}","name":""}'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: '114',
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'mkmv.livekit.cloud',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'mkmv.livekit.cloud',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 1526,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /twirp/livekit.RoomService/UpdateParticipant HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tQWRtaW4iOnRydWUsInJvb20iOiIxOmF2OjEifSwiaWF0IjoxNzAyNjAzMjYwLCJuYmYiOjE3MDI2MDMyNjAsImV4cCI6MTcwMjYwMzg2MCwiaXNzIjoiQVBJbUxBTnlBUE5Fa2tVIn0.LjGQsQFTcDmwQwowmf5Fr4674TPtMtxyuDNy8ayNPew\r\n' +
      'User-Agent: axios/1.5.1\r\n' +
      'Content-Length: 114\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: mkmv.livekit.cloud\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 2,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/twirp/livekit.RoomService/UpdateParticipant',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://mkmv.livekit.cloud/twirp/livekit.RoomService/UpdateParticipant',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 10,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'mkmv.livekit.cloud',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 114,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://mkmv.livekit.cloud/twirp/livekit.RoomService/UpdateParticipant',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: Object [AxiosHeaders] {
      'content-length': '57',
      'content-type': 'application/json',
      date: 'Fri, 15 Dec 2023 01:21:15 GMT',
      vary: 'Origin',
      connection: 'close'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      baseURL: 'https://mkmv.livekit.cloud/',
      method: 'post',
      url: '/twirp/livekit.RoomService/UpdateParticipant',
      data: '{"room":"1:av:1","identity":"streaming_bot","metadata":"{\\"timestamp\\":1702603227817,\\"iteration\\":30}","name":""}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '114',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /twirp/livekit.RoomService/UpdateParticipant HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWRlbyI6eyJyb29tQWRtaW4iOnRydWUsInJvb20iOiIxOmF2OjEifSwiaWF0IjoxNzAyNjAzMjYwLCJuYmYiOjE3MDI2MDMyNjAsImV4cCI6MTcwMjYwMzg2MCwiaXNzIjoiQVBJbUxBTnlBUE5Fa2tVIn0.LjGQsQFTcDmwQwowmf5Fr4674TPtMtxyuDNy8ayNPew\r\n' +
        'User-Agent: axios/1.5.1\r\n' +
        'Content-Length: 114\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: mkmv.livekit.cloud\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/twirp/livekit.RoomService/UpdateParticipant',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'mkmv.livekit.cloud',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { code: 'internal', msg: 'operation cannot be completed' }
  }
}
```
</details>

### PR DESCRIPTION
**Pull request by lukasIO**
fixes #123
fixes #22

### CODE REVIEW

**Review by ThomasBurgess2000 — APPROVED** [review]

File: src/TwirpRPC.ts [hunk 1]
```diff
@@ -29,22 +29,23 @@ export class TwirpRpc {
...
+      method: 'POST',
+      headers: {
+        'Content-Type': 'application/json;charset=UTF-8',
+        ...headers,
+      },
+      body: JSON.stringify(data),
     });
+
+    if (!response.ok) {
+      throw new Error(response.statusText);
```
Comment (ThomasBurgess2000) [inline src/TwirpRPC.ts:46]: perhaps throw entire response body if it contains useful error information? or at least status code as well

File: src/TwirpRPC.ts [hunk 2]
```diff
@@ -29,22 +29,23 @@ export class TwirpRpc {
...
+    }
+    const parsedResp = await response.json();
```
Comment (ThomasBurgess2000) [inline src/TwirpRPC.ts:48]: can json parsing ever fail? perhaps also check if Content-Type header is JSON in case this ever handles non-JSON responses?

**Review by davidzhao — APPROVED** [review]
awesome fix!

File: src/TwirpRPC.ts (hunk 2 above)
Comment (lukasIO) [reply src/TwirpRPC.ts:48]: In theory json parsing can fail. In that case an exception will be raised and the api call will throw with that exception

File: src/TwirpRPC.ts (hunk 1 above)
Comment (lukasIO) [reply src/TwirpRPC.ts]: that's a good call. Made the error message no explicit for cases where there might be no status text set.
